language: cpp
compiler: g++-6
install: mkdir -p core/resources && wget https://www.dropbox.com/s/iw6yuk8naanppn0/HandRanks.dat?dl=0 -O core/resources/HandRanks.dat
script: cd core && make && make test
