dist: trusty
sudo: require
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      
compiler: g++-6
install: mkdir -p core/resources && wget https://www.dropbox.com/s/iw6yuk8naanppn0/HandRanks.dat?dl=0 -O core/resources/HandRanks.dat
script: make CXX=g++-6 test
